name: SyncToGitee

on:
  push:
    branches:
      - master
      - v1.5.0-feat-app-refactor
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/go-atomci
        dst: gitee/goatom
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "atomci"
        debug: true
        # force_update: true
        account_type: org
        # src_account_type: org
        # dst_account_type: org
